nome = ('Pietro')
idade = int (17)
linguagemFavorita = ('Python')
ano_atual = int (2025)
anoDoSeuNascimento = int (ano_atual - idade)
print (f'O meu nome é {nome},\nNasci em {anoDoSeuNascimento}\nTenho {idade} anos e\nMinha linguagem de programação favorita é {linguagemFavorita}')
