nome = input ('Escreva seu nome ')
idade = int (input('Insira seu idade '))
linguagemFavorita = input ('Coloque a sua linguagem favorita ')
ano_atual = int (2025)
anoDoSeuNascimento = int (ano_atual - idade)
print (f'O meu nome é {nome},\nNasci em {anoDoSeuNascimento}\nTenho {idade} anos e\nMinha linguagem de programação favorita é {linguagemFavorita}')
